POST http://localhost:3000/api/users
Content-Type: application/json

{
  "email": "nomgnenoel@gmail.com",
  "famillyName": "FOKA",
  "givenName": "Joel"
}

###

POST http://localhost:3000/api/companies
Content-Type: application/json

{
  "email": "nomgnenoel@gmail.com",
  "companyName": "Numerical Book It"

}

###

GET http://localhost:3000/api/companies?email=nomgnenoel@gmail.com

###

DELETE http://localhost:3000/api/companies
Content-Type: application/json

{
  "id": "cm5jj2t1s0003viuoe6q4i2r4"
}

###

PATCH  http://localhost:3000/api/companies
Content-Type: application/json

{ 
  "id": "cm5krffkd0002vif0lgb9c481", 
  "creatorEmail": "nomgnenoel@gmail.com", 
  "employeeEmail": "test@test.com", 
  "action": "ADD" 
}
